version: '3.3'
services:
    client:
      build: ./client
      image: yoloclient:version1
      ports:
          - "3000:3000"
      depends_on:
          - backend
      networks:
          - yoloappnetwork
    backend:
      build: ./backend
      image: yolobackend:version1
      ports:
          - "5000:5000"
      depends_on:
          - mongo
      networks:
          - yoloappnetwork
    mongo:
      image: mongo
      restart: always
      volumes: 
          - ./datadir:/data/db
      ports:
          - 27017:27017
      networks:
          - yoloappnetwork
networks:
    yoloappnetwork:
        driver:bridge

